### PR TITLE
sof-kernel-log-check: ignore an ime_me error on CML_RVP_SDW

### PR DESCRIPTION
**Pull request by aiChaoSONG**
Fixes: #389

Signed-off-by: Amery Song <chao.song@intel.com>

### CODE REVIEW

**Review by xiulipan — APPROVED** [review]

**Review by marc-hb — COMMENTED** [review]
Please move very platform-specific errors like this one to the
```shell
case "$platform" in
```
section so we can track them accurately.

**Review by marc-hb — COMMENTED** [review]
Also, this error is already there, it only needs a wildcard:
```
ignore_str="$ignore_str"'|mei_me 0000:00:16\..: hw_start failed ret = -62'
```

**Comment by aiChaoSONG** [comment]
@marc-hb No, not the same thing as the exist one, one is  hw_start, the other is hw_reset.

**Comment by marc-hb** [comment]
Refined in #463

**Pull request merged**
