### PR TITLE
remove plughw in alsabat test

### PR DESCRIPTION
**Pull request by keqiaozhang**
Add channel and rate options support in alsabat test and
remove use of plughw to run alsabat test at hw level w/o
any conversions done by alsa-lib.

Signed-off-by: Zhang Keqiao <keqiao.zhang@linux.intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Sorry I don't understand why the number of channels is hardcoded for playback but not for capture.

I also find the code comment not visible enough, I think a `dlogw` or at the very least a `dlogi` warning should be printed.

**Comment by keqiaozhang** [comment]
> Sorry I don't understand why the number of channels is hardcoded for playback but not for capture.
> 
> I also find the code comment not visible enough, I think a `dlogw` or at the very least a `dlogi` warning should be printed.

This script is for sof playback test, as our sof doesn't support 1 channel(mono wav) playback, so I set the channel number to 2.  

Since we use different USB sound cards in CI, old USB sound cards only support 1 channel capture and new USB sound cards support 2 channels, so I set the channel number of capture as an option( -C ), we can specify it in the alsabat-playback.csv file for each platform.   
We plan to buy more USB sound cards to replace the old one in CI. After that, we can remove this option and test 2 channels for both playback and capture.

**Review by aiChaoSONG — DISMISSED** [review]
some usb card now support stereo channel, thanks for the fix.

**Comment by xiulipan** [comment]
@keqiaozhang Need to take care nocodec platforms, they do not use USB loopback.

**Review by xiulipan — APPROVED** [review]

**Comment by aiChaoSONG** [comment]
SOFCI TEST

**Comment by aiChaoSONG** [comment]
The failure on APL_NOCODEC is not caused by this PR, but need to fine tune.

**Review by aiChaoSONG — APPROVED** [review]

**Pull request merged**
