### PR TITLE
test: add test mode and count parameter for xrun injection test

### PR DESCRIPTION
**Pull request by keqiaozhang**

### CODE REVIEW

**Comment by wenqingfu** [comment]
seems you brought in the patch for #31 together accidentally?

**Comment by keqiaozhang** [comment]
@wenqingfu , Yes,  I should submit these 2 patches as one patch set.

**Comment by aiChaoSONG** [comment]
@keqiaozhang @wenqingfu Can we close #31, and leave #32 for review and merge? may be need to change title of #32

**Comment by stripes416** [comment]
This also LGTM.

**Pull request merged**
