### PR TITLE
kmod: add new SoundWire codecs

### PR DESCRIPTION
**Pull request by plbossart**
Missing max98363, rt712-sdca, rt712-sdca-dmic

### CODE REVIEW

**Review by marc-hb — APPROVED** [review]
Two separate commits would have made the changes a bit faster to review.

**Review by bardliao — APPROVED** [review]

**Comment by marc-hb** [comment]
I suspect this just caused a regression:

https://sof-ci.ostc.intel.com/#/result/planresultdetail/26399?model=TGLU_RVP_NOCODEC_IPC4ZPH&testcase=check-kmod-load-unload
```
RMMOD	regmap_sdw
rmmod: ERROR: Module regmap_sdw is in use by: snd_soc_rt712_sdca_dmic snd_soc_rt712_sdca
```

Same error across multiple devices

**Comment by marc-hb** [comment]
Failing the same in totally unrelated https://sof-ci.01.org/linuxpr/PR4376/build5091/devicetest/index.html

**Comment by bardliao** [comment]
@marc-hb @plbossart Below change can fix the issue.
```patch
diff --git a/tools/kmod/sof_remove.sh b/tools/kmod/sof_remove.sh
index 45cb3e4..d87096e 100755
--- a/tools/kmod/sof_remove.sh
+++ b/tools/kmod/sof_remove.sh
@@ -210,8 +210,8 @@ remove_module snd_soc_rt298
 remove_module snd_soc_rt700
 remove_module snd_soc_rt711
 remove_module snd_soc_rt711_sdca
-remove_module snd-soc-rt712-sdca
-remove_module snd-soc-rt712-sdca-dmic
+remove_module snd_soc_rt712_sdca
+remove_module snd_soc_rt712_sdca_dmic
 remove_module snd_soc_rt715
 remove_module snd_soc_rt715_sdca
 remove_module snd_soc_rt1308
```
`sudo modprobe -r snd-soc-rt712-sdca` works, but somehow `snd-soc-rt712-sdca` doesn't work in sof_remove.sh

**Comment by marc-hb** [comment]
Thanks @bardliao , this looks great! Can you please submit the PR?

> but somehow snd-soc-rt712-sdca doesn't work in sof_remove.sh

That's because sof_remove.sh searches for the "real" name in /proc/modules.

**Comment by marc-hb** [comment]
> it's probably a miss where the RT712 was not included in the build when this change was added. 

Thanks, that would explain.

> Not sure what this matters, usually modprobe does not care.

As mentioned above the script searches /proc/modules so it can show a nice message that the module was already unloaded as opposed to trying to unload it anyway, having to ignore errors and then fail to catch actual failures to unload.

**Pull request merged**
