### PR TITLE
test-case: add set -e to 7 function test

### PR DESCRIPTION
**Pull request by RuiqingX**
Fixes: #312

Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

### CODE REVIEW

**Comment by RuiqingX** [comment]
I have done some tests on sh-jsl-rvp-hda-01 and sh-tgl-shuri-hda-02.

**Comment by marc-hb** [comment]
For a change like this I think we really need to wait for a green CI + make sure the next daily test run after merge is all green too.

**Comment by aiChaoSONG** [comment]
I have checked the test result, The timeout on CML_RVP_SDW with alsabat test case is actually a failure, root cause is that the test framework doesn't know the exit code 21, so it fallback to timeout, but I don't think it is related to the PR. @RuiqingX Maybe you go to `jf-cml-rvp-sdw-3` or other CML_RVP_SDW and run a manual test with the alsabat case?

**Comment by RuiqingX** [comment]
I've checked with Xiuli just now, and I have validated this issue on sh-cml-rvp-sdw-04, test result is pass.

**Comment by keqiaozhang** [comment]
> I have checked the test result, The timeout on CML_RVP_SDW with alsabat test case is actually a failure, root cause is that the test framework doesn't know the exit code 21, so it fallback to timeout, but I don't think it is related to the PR. @RuiqingX Maybe you go to `jf-cml-rvp-sdw-3` or other CML_RVP_SDW and run a manual test with the alsabat case?

alsabat failed on CML-RVP-SDW is caused by the codec prefix_name change in machine description, so the amixer control names 
 have also changed accordingly. I have submitted a[ PR105](https://gitlab.devtools.intel.com/sof-ci/sof-framework/-/merge_requests/105) to fix it.

**Review by aiChaoSONG — APPROVED** [review]
LGTM， Thanks @keqiaozhang for correcting me on the alsabat fi, good to know that.

**Pull request merged**
