### PR TITLE
make start_test() optional: part 1

### PR DESCRIPTION
**Pull request by marc-hb**
This is the first step towards fixing:
- #1112 
- #1169

### CODE REVIEW

**Comment by marc-hb** [comment]
mtrace-reader.py hangs the following test: https://sof-ci.01.org/softestpr/PR1170/build267/devicetest/index.html?model=TGLU_RVP_NOCODEC-ipc4&testcase=check-kmod-load-unload-after-playback

Needs more work.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
GLK BOB hung in https://sof-ci.01.org/softestpr/PR1170/build311/devicetest/index.html?model=GLK_BOB_DA7219-ipc3&testcase=check-kmod-load-unload but that happened before this PR, already filed at:
- https://github.com/thesofproject/linux/issues/4924
Everything else green in stable-v2.2

CAVS https://sof-ci.01.org/softestpr/PR1170/build312/devicetest/index.html is all green.

ACE https://sof-ci.01.org/softestpr/PR1170/build313/devicetest/index.html is all green except for a couple suspend/resume tests still running.

This is good to go!

**Review by fredoh9 — APPROVED** [review]
Looks like good starting point as part 1.
Looking forward to seeing part 2

**Comment by fredoh9** [comment]
SOFCI TEST

**Comment by fredoh9** [comment]
The device test is triggered to test lnl pr test

**Comment by marc-hb** [comment]
There's no DSP runtime PM on `ba-lnlm-rvp-hda-01` https://sof-ci.01.org/softestpr/PR1170/build320/devicetest/index.html?model=LNLM_RVP_HDA&testcase=check-runtime-pm-status 

I just reproduced even without this PR, so it's unrelated. Merging.

**Comment by marc-hb** [comment]
That's because `/sys/devices/pci0000:00/0000:00:1f.3/power/control` is `on` on that `ba-lnlm-rvp-hda-01` device instead of `auto` on other devices. Even after a reboot. Why?

**Pull request merged**
