### PR TITLE
volume-basic-test.sh: search PGA name without case sensitive

### PR DESCRIPTION
**Pull request by fredoh9**
PGA name could be in uppercase or lowercase. Especially topology2 change
makes pga name in lowercase.

### CODE REVIEW

**Review by ranj063 — DISMISSED** [review]
Thanks @fredoh9

**Comment by marc-hb** [comment]
@fredoh9 could you check the failures in https://sof-ci.01.org/softestpr/PR619/build589/devicetest/ and make sure they're all already tracked somewhere else?

**Comment by fredoh9** [comment]
> @fredoh9 could you check the failures in https://sof-ci.01.org/softestpr/PR619/build589/devicetest/ and make sure they're all already tracked somewhere else?

Sure, I don't see any error in volume test case, but for other errors, I will double check this is known issues and being tracked by issuess.

**Review by marc-hb — APPROVED** [review]
The only force-push difference in https://github.com/thesofproject/sof-test/compare/db3e6688d25f5c2fa4d0041fa0c6e902dea2bd4b..716e42f7cc8bf90b2608e436cc8a933fd573a9b9 is adding  Signed-off-by

The new test run is https://sof-ci.01.org/softestpr/PR619/build591/devicetest/

**Review by aiChaoSONG — APPROVED** [review]
LGTM
Failures in test result are not related.

**Pull request merged**
