### PR TITLE
CODEOWNERS: remove 15 lines to simplify

### PR DESCRIPTION
**Pull request by marc-hb**
We're not that big.

Also try to use new test-maintainers team.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
> Also try to use new test-maintainers team.

Apparently not possible until sof-test gets added to https://github.com/orgs/thesofproject/teams/test-maintainers/repositories

**Comment by plbossart** [comment]
> > Also try to use new test-maintainers team.
> 
> Apparently not possible until sof-test gets added to https://github.com/orgs/thesofproject/teams/test-maintainers/repositories

I added this repo but I am not sure what permissions you want for this team?

**Comment by marc-hb** [comment]
> I added this repo but I am not sure what permissions you want for this team?

I don't know github enough to know either :-(

Right now it's only "read" and that was enough difference to allow using the new teams in the "request" field in the top right.

I'm going to merge this now because I don't think it's possible to test CODEOWNERS without merging it. It's easy enough to revert and for sure it's not going to break anything else.

**Comment by marc-hb** [comment]
> The people you choose as code owners must have write permissions for the repository. When the code owner is a team, that team must have write permissions, even if all the individual members of the team already have write permissions directly, through organization membership, or through another team membership.

**Comment by marc-hb** [comment]
Thanks, it works now. Typo fixed in #319

**Pull request merged**
