### PR TITLE
Shellcheck check xrun injection

### PR DESCRIPTION
**Pull request by greg-intel**
Various shellcheck quoting issues and other fixes.

Signed-off-by: Greg Galloway <greg.galloway@intel.com>

### CODE REVIEW

**Review by marc-hb — APPROVED** [review]

**Comment by marc-hb** [comment]
No test has been run yet after 1h, this is not normal:

Screenshot 2023-06-14 at 15 57 34

**Comment by greg-intel** [comment]
SOFCI TEST

**Comment by greg-intel** [comment]
Test failures are unrelated, this test doesn't run during PR testing.

**Comment by marc-hb** [comment]
> Test failures are unrelated, this test doesn't run during PR testing.

So you gave it a decent round of testing locally, correct?

**Comment by greg-intel** [comment]
> So you gave it a decent round of testing locally, correct?

With pretty much every little change I made.

**Comment by marc-hb** [comment]
Thanks! Let's merge this first thing on Monday

**Review by marc-hb — APPROVED** [review]

**Pull request merged**
