### PR TITLE
ignore_str filter updates from Pierre

### PR DESCRIPTION
**Pull request by marc-hb**
Re-submitting the first part of #354 . This only updates the `ignore_str` filters and does not have any actual code change.

### CODE REVIEW

**Comment by marc-hb** [comment]
The shellcheck warnings all predate this PR.

Summary of the issues in device-test results:
- The only "real" failures are caused by this ICL fw reboot issue:
```
kernel: [  486.166822] sof-audio-pci 0000:00:1f.3: status = 0x00000000 panic = 0x00000000
```
- All the other issues are SKIPs (or SKIPs under a different name like "Not Applicable"), except for:
- No test was run on CML because the device was not available.

As this PR performs a number of CML-related changes, I consider it ready for review but not for merge yet.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
The CML situation just got worse today: all CML tests fail with `File /lib/firmware/intel/sof/sof-cml.ri is not found!` (or `sof-cnl.ri` not found for `CML_MANTIS_HDA`.

This is of course not specific to this PR, here are some other random examples:
https://sof-ci.01.org/sofpr/PR3389/build7120/devicetest/
https://sof-ci.01.org/linuxpr/PR2422/build4438/devicetest/

This started happening across all git repos and all CML devices in the last 12 hours.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> This started happening across all git repos and all CML devices in the last 12 hours.

Root caused by @fredoh9 to an internal script change merged 11 hours ago and fixed by @fredoh9 just now.

All CML devices look fine now in https://sof-ci.01.org/softestpr/PR362/build152/devicetest, I think this is merge-ready (remember it was already reviewed in #354)

**Review by xiulipan — APPROVED** [review]
Looks good, this seems ignore most new error logs from our test.

**Comment by marc-hb** [comment]
Removal of some exclusions partially reverted in #395 to support testing with older kernels.

Simplifying the triple negation: need to ignore some errors again to support testing with older kernels.

**Pull request merged**
