### PR TITLE
[SKIP CI] migrate alsa_settings from internal sof-framework repo

### PR DESCRIPTION
**Pull request by fredoh9**
alsa settings per platform is required before running check-alsabat.sh.
These scripts have proper gain settings, required switches on etc.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
I assume these files are strictly identical to the original ones?

Can you add a second commit that starts each file with `set -e`? I think it's a great opportunity.

Different commit to keep the first commit easy to compare with the original.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR736/build788/devicetest/?model=ADLP_RVP_NOCODEC&testcase=verify-kernel-boot-log looks like a misconfiguration.

**Comment by fredoh9** [comment]
I put "SKIP CI" this is nothing to do with CI yet

**Review by marc-hb — DISMISSED** [review]
I'm approving the idea, I did not compare the files with the originals

**Comment by fredoh9** [comment]
There are some changes in past a few days. :) I will re-sync and update this.

**Comment by marc-hb** [comment]
> There are some changes in past a few days. :) I will re-sync and update this.

Actually: please provide the internal SHA1 you copy from when you do so.

**Review by marc-hb — APPROVED** [review]
Again, approving the logic but I didn't compare this to the internal copy.

**Pull request merged**
