### PR TITLE
hijack.sh: fail if the logger trace is empty

### LINKED ISSUE #297: Check for a valid trace for ALL tests
We need to double-check that the trace is functional and that sof-logger reports at least the firmware details and a dai trigger.

If there is no trace then there's no point in checking results and debugging further.

cc:
- #1075
- https://github.com/thesofproject/sof/pull/7955
- #1075
- https://github.com/thesofproject/sof-test/pull/1084

+ many others, follow the links.

### PR DESCRIPTION
**Pull request by marc-hb**
_Resubmit #383 to new `main` branch_

Does not completely fixes #297 but goes a long way.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
The less ambitious #629 passed except on BYT where it fails consistently

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR662/build672/devicetest/ is all green!

**Review by aiChaoSONG — APPROVED** [review]
Note that sof-logger is started by `func_lib_start_log_collect` in lib.sh,  and some cases which only do kernel log check don't call this.

**Comment by marc-hb** [comment]
> and some cases which only do kernel log check don't call this.

`if [ "X$SOF_LOG_COLLECT" == "X1" ]; then` on line 27 should take care of that case. These tests would have failed otherwise.

Merging, if BYT (or other?) starts failing this test again then the #663 workaround should help.

**Pull request merged**
