### PR TITLE
test-case: unify code style for kernel log check function calls

### PR DESCRIPTION
**Pull request by aiChaoSONG**
As Bin add check for kernel log check return value in https://github.com/thesofproject/sof-test/pull/203, and use a new code style, this patch align code style around all of the repo.

### CODE REVIEW

**Comment by marc-hb** [comment]
```shell
dloge "Catch error in dmesg" && exit 1
```
I don't understand the `&&`. If there's an issue in `dloge` and `dloge` fails then the code will keep running. That seems wrong.

**Comment by Bin-QA** [comment]
https://github.com/thesofproject/sof-test/blob/master/case-lib/logging_ctl.sh#L36

if it is failed, it will meet more serious problem

**Comment by marc-hb** [comment]
Sorry I still don't understand why `&&` instead of `;`

**Comment by aiChaoSONG** [comment]
> Sorry I still don't understand why `&&` instead of `;`

@Bin-QA Marc is right, whatever the return value of `dloge` is, we want the `exit` to be excuted, so need to refine again in a new PR.

**Comment by Bin-QA** [comment]
yes, Marc is right,  
my point is when `echo` failed,  
`exit` seems also couldn't been execute

**Comment by aiChaoSONG** [comment]
@marc-hb I have submit a patch to fix this, https://github.com/thesofproject/sof-test/pull/211. I am graduated from university less than a year, and not as experienced as you, really appreciate your review and suggestions.

**Pull request merged**
