### PR TITLE
Update module dependencies: take2

### PR DESCRIPTION
**Pull request by plbossart**
PR #1130 was not good enough...

### CODE REVIEW

**Comment by marc-hb** [comment]
> it's been a while since we renamed PCI/ACPI drivers, remove all stuff.

Roughly how long ago? Time or kernel tag.

**Comment by plbossart** [comment]
no results, it seems we have to manually crank the server to do its job. Gah.

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by plbossart** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Review by keqiaozhang — APPROVED** [review]
LGTM & CI test passed, no kmod failures.

**Pull request merged**
