### PR TITLE
lib.sh: add 2nd .ldc fallback in /lib/firmware/intel/sof/sof-abc.ldc

### PR DESCRIPTION
**Pull request by marc-hb**
From a developer perspective this makes easier to deploy the .ldc
dictionary at the same time than the firmware.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
One ALSABAT test failed in https://sof-ci.01.org/softestpr/PR615/build588/devicetest/?model=CML_RVP_SDW&testcase=check-alsabat-headset-playback and BSW failed to boot - nothing related to this.

**Comment by marc-hb** [comment]
This is required for sof-test to use `.ldc` files installed by https://github.com/thesofproject/sof/pull/3845

**Review by aiChaoSONG — APPROVED** [review]
LGTM.
FYI， once we transfer to zephyr SOF, we will use tools here: https://github.com/zephyrproject-rtos/zephyr/tree/master/boards/xtensa/intel_adsp_cavs15/tools, which don't require LDC file like sof-logger does.

**Comment by marc-hb** [comment]
Thanks @aiChaoSONG . Does Zephyr support some other kind of dictionary yet to save memory? If yes where is the dictionary found?

**Review by kv2019i — APPROVED** [review]
Thanks @marc-hb , this is useful!

**Review by fredoh9 — APPROVED** [review]
LGTM, thanks!

**Comment by aiChaoSONG** [comment]
> Thanks @aiChaoSONG . Does Zephyr support some other kind of dictionary yet to save memory? If yes where is the dictionary found?

The tools there can be used directly, don't need to specify some kind of LDC file. but I am not sure if there 'is' some kind of dict or not.

**Comment by marc-hb** [comment]
> but I am not sure if there 'is' some kind of dict or not.

Searched some archives and found this: https://github.com/zephyrproject-rtos/zephyr/pull/30539

**Comment by aiChaoSONG** [comment]
> For now the SOF logger should work with SOF+Zephyr?

@marc-hb sof-logger requires the `*.ldc` file to run, but SOF+Zephyr don't generate it.

**Pull request merged**
