### PR TITLE
tplgtool2: parse vendor array for DAPM widgets only and raise error for unknown vendor types 

### PR DESCRIPTION
**Pull request by miRoox**
Previously, parsing `cavs-tgl-nocodec.tplg` got stuck because it treat the NHLT table in the manifest private data as a vendor array and didn't catch the unexpected vendor tuple types.

These 2 parts to fix it and improve soundness:

1. parse vendor array for DAPM widgets only
2. raise error for unknown vendor types

Signed-off-by: Yongan Lu <yongan.lu@intel.com>

### CODE REVIEW

**Review by aiChaoSONG — APPROVED** [review]

**Comment by marc-hb** [comment]
Could this fix the missing topology in https://github.com/thesofproject/sof-test/pull/958 ?

cc: @plbossart

**Comment by fredoh9** [comment]
It was stuck at a contruct function. glad found the fix.

```
...
File "/usr/lib/python3/dist-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3/dist-packages/construct/core.py", line 3917, in _parse
    keyfunc = evaluate(self.keyfunc, context)
  File "/usr/lib/python3/dist-packages/construct/core.py", line 198, in evaluate
    return param(context) if callable(param) else param
  File "/usr/lib/python3/dist-packages/construct/expr.py", line 184, in __call__
    def __call__(self, obj, *args):
```

**Comment by fredoh9** [comment]
Looking at the failure, it released the stuck after 30min. I was wondering how it was bailed out from the stuck itself. It looks exit due to kernel Out of memory error. Then the script crashed and exit with 255.

`[ 1720.045898] kernel: Out of memory: Killed process 1457 (python3) total-vm:17467848kB, anon-rss:15470464kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:33780kB oom_score_adj:0`

**Comment by marc-hb** [comment]
Out of memory looks like a really bad `construct` bug. Which machine does this tool currently run on? I'm curious about the `construct` version.

**Comment by miRoox** [comment]
Tested on most of our in-use models: https://sof-ci.sh.intel.com/#/result/planresultdetail/15355?model=TGLU_RVP_NOCODEC_IPC4ZPH&testcase=verify-kernel-boot-log, the errors on verify-kernel-boot-log is unrelated.

**Comment by miRoox** [comment]
> Out of memory looks like a really bad `construct` bug. Which machine does this tool currently run on? I'm curious about the `construct` version.

It's not a `construct` bug, just like I implicitly write an infinitely recursive function in this case. But of course, it would be better if `construct` provides something like max iteration.

**Pull request merged**
