### PR TITLE
Add a new test case to check kernel boot log

### PR DESCRIPTION
**Pull request by aiChaoSONG**
tested on several DUTs, works fine.

### CODE REVIEW

**Comment by marc-hb** [comment]
Why not just check the logs from boot when no checkpoint is set?

The worse that can happen is: some test forgets to set the checkpoint, then it might fail because of earlier tests. That's a very easy lesson to learn and fix.

**Comment by aiChaoSONG** [comment]
> Why not just check the logs from boot when no checkpoint is set?

Previously, we have experience an issue which the test log is too big in stress test, that's why we only collect log output within the period of running test case, or under some condition, only collect logs from the latest iteration.
Now, I force every test case to explicit setup_kernel_check_point or disable_kernel_check_point in my journalctl PRs. `die` is not good, I agree with you, so https://github.com/thesofproject/sof-test/pull/661 is a good fix.

**Review by marc-hb — APPROVED** [review]
> we have experience an issue which the test log is too big in stress test,

I didn't think about this, thanks for the info.

**Review by fredoh9 — APPROVED** [review]
looks good. Next step, we need to add this new test  to first test case of all(or one of first)

**Pull request merged**
