### PR TITLE
test-case: add set -e to 5 function test

### PR DESCRIPTION
**Pull request by RuiqingX**
test-case: add set -e to 5 function test

Fixes: #312

Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

### CODE REVIEW

**Comment by RuiqingX** [comment]
SOFCI TEST

**Comment by xiulipan** [comment]
@RuiqingX I think some case may not be able to run with `set -e`. Please try with case by case locally first.

**Comment by aiChaoSONG** [comment]
@RuiqingX Next time when you want to close an issue or a PR, please give some reason.

Ruiqing tested that directly adding set -e to 7 cases will not cause any problem, he will submit a new PR with that changes to that 7 cases. @RuiqingX  Can you list the script names which `set -e` will cause problems?

**Comment by RuiqingX** [comment]
These scripts will have problems after adding set -e:
check-xrun-injection.sh
multiple-pipeline-playback.sh
multiple-pipeline-capture.sh
test-speaker.sh
check-pause-release-suspend-resume.sh
check-sof-logger.sh
check-signal-stop-start.sh
check-runtime-pm-status.sh
check-runtime-pm-double-active.sh
verify-ucm-config.sh
simultaneous-playback-capture.sh

**Comment by marc-hb** [comment]
Thanks @RuiqingX , if you're not sure how to make a script compatible with `set -e` then feel free to contact me and I will help.

A good start for any script is to fix shellcheck warnings first.

One script at a time to minimize any unexpected CI impact.

**Comment by marc-hb** [comment]
Newer PR with a couple scripts from this list + other scripts: #400

**Pull request closed without merging**
