### PR TITLE
kmod-case: fix case exit with module unloaded

### PR DESCRIPTION
**Pull request by aiChaoSONG**
Fixes: #351

Signed-off-by: Amery Song <chao.song@intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@aiChaoSONG What I am think here is could module reload successfully when error already happen? It may break the device directly.
what @lyakh wants in https://github.com/thesofproject/sof-test/issues/351 is that we should reset the DUT if error happen in those test case.

I think we should handle this in our framework.

**Comment by xiulipan** [comment]
@marc-hb we already put all suspend/resume and kmod test in last.
I am also working on the framework in CI to reset the device.

**Comment by aiChaoSONG** [comment]
@marc-hb @xiulipan maybe we should  depend on the framework to resolve this. close ?

**Comment by marc-hb** [comment]
> @marc-hb @xiulipan maybe we should depend on the framework to resolve this. close ?

When you write "depend on" I read "wait for". Why not but for how long? Do we need another workaround in the mean time?

Ask  the submitter in #351

**Comment by aiChaoSONG** [comment]
This is a bad try to solve #351,  I agree that if issue happens in kmod test, reset DUT is a good way to restore. let's close this.

**Pull request closed without merging**
