### PR TITLE
check-sof-logger: switch to new find_ldc_file() function

### PR DESCRIPTION
**Pull request by marc-hb**
2 commit messages.

### CODE REVIEW

**Comment by marc-hb** [comment]
The only two failures in https://sof-ci.01.org/softestpr/PR626/build597/devicetest/ are platform-specific `check-suspend-resume` timeouts tracked (among others?) in internal issues 667 and 670. This PR does not affect suspend/resume. The logger test passed across all platforms.

**Comment by marc-hb** [comment]
None of the shellcheck failures in check-suspend-resume are new

**Comment by marc-hb** [comment]
No new shellcheck warning in https://github.com/thesofproject/sof-test/pull/626/checks?check_run_id=2037177639

**Review by fredoh9 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
