### PR TITLE
case-lib/apause.exp: fix error message and comments 

### PR DESCRIPTION
**Pull request by marc-hb**
cc:
- https://github.com/thesofproject/sof-test/pull/931
- https://github.com/thesofproject/linux/issues/5048
- https://github.com/thesofproject/linux/issues/5109
- https://github.com/thesofproject/linux/pull/5041

### CODE REVIEW

**Comment by marc-hb** [comment]
Mmmm... why did https://sof-ci.01.org/softestpr/PR1222/build668/devicetest/index.html (and others) run with the old, broken SOF commit [d629e521020c](https://github.com/thesofproject/sof/commit/d629e521020c7d2375ed4696d0937c5cdd444e62)? Weird.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Known LNL pause issue https://github.com/thesofproject/linux/issues/5109
in https://sof-ci.01.org/softestpr/PR1222/build676/devicetest/index.html?model=LNLM_RVP_NOCODEC&testcase=check-pause-resume-capture-100

Everything else 100% green.

**Review by fredoh9 — APPROVED** [review]
Thank you for better description

**Pull request merged**
