### PR TITLE
Travis: update OS and add numpy and scipy packages

### PR DESCRIPTION
**Pull request by aiChaoSONG**

### CODE REVIEW

**Comment by marc-hb** [comment]
Unfortunately we need to wait a few hours :-(

**Comment by aiChaoSONG** [comment]
@marc-hb The travis job is still queuing, is there any problem with travis or the code change is not correct?

**Comment by marc-hb** [comment]
I think Travis has just been incredibly slow. On November 19 they reduce the capacity from 500 down to 400 :-(
https://www.traviscistatus.com/#month

I will look at github actions soon

**Review by marc-hb — APPROVED** [review]
https://travis-ci.org/github/thesofproject/sof-test/builds/747115385 successful about 30 hours (!) after submission...

**Pull request merged**
