### PR TITLE
test-case: new run-all-tests.sh 

### PR DESCRIPTION
**Pull request by bardliao**
The scrupt is to run all test cases.

Signed-off-by: Bard Liao <yung-chuan.liao@linux.intel.com>

@xiulipan @aiChaoSONG I don't know who is the author. Please help to add the author's signed-off-by if you know who he/she is.

### CODE REVIEW

**Comment by marc-hb** [comment]
Multi-dimensional arrays require workarounds in bash but using `test_$t` functions works fine:

```shell
set -e
test_play_l100()
{
    ./check-playback.sh -d "$dur" -l 100 -r 1
}
test_play_r50()
{
    ./check-playback.sh -d "$dur"  -l 1 -r 50
}
main()
{
    local failures=0

    for t in play_l100 play_r50; do
        printf 'starting test_%s\n' $t
        test_$t || : $((failures++))

    done

    exit "$failures"
}

```

**Comment by bardliao** [comment]
@marc-hb Thanks for the suggestion. Updated.

**Comment by marc-hb** [comment]
Nit: could you move the test functions to the end of the file? They're the least likely to change in the future.

**Comment by bardliao** [comment]
> Nit: could you move the test functions to the end of the file? They're the least likely to change in the future.

Done

**Pull request merged**
