### PR TITLE
tools: fix a pipeline formats assignment error

### PR DESCRIPTION
**Pull request by aiChaoSONG**
check the comments in the code for a reason.

### CODE REVIEW

**Review by fredoh9 — DISMISSED** [review]
LGTM, thank you for adding comments as well

**Comment by marc-hb** [comment]
@aiChaoSONG can you give an example of test failure or failed scenario? If not in the commit message then at least here in the PR comments.

**Comment by aiChaoSONG** [comment]
@marc-hb The issue will not cause test failure, issue description is added in commit message.

**Comment by marc-hb** [comment]
Interesting that we have no test that can detect this... Should we have one? Would it be difficult to have one or modify an existing one?

**Comment by aiChaoSONG** [comment]
@marc-hb I don't think we should have a case for this, this is a one-time issue and now we fix it ! It is an issue of topology parser in sof-test, and will not impact any test. To enable a case for this, we need to compare the parsed formats by sof-tplgreader.py with the formats from topology conf or m4 source. Too much effort, doesn't worth a try.

**Comment by marc-hb** [comment]
Thanks, so now I wonder how you found this but it's not important, never mind.

**Comment by aiChaoSONG** [comment]
@marc-hb Keyon and I are working on TGL1.0 release this week. the new feature "codec adapter" can only work under S32_LE currently. So we need to run aplay with S32_LE, but the topology parser tells that there is no S32_LE support for the codec adapter pipeline. After checking the topology conf, the S32_LE is actually there, this drives me to debug the parser.

Assume this issue not fixed, and the playback pipeline supports all formats that the capture pipeline supports, we may never find it !

**Comment by marc-hb** [comment]
> So we need to run aplay with S32_LE, but the topology parser tells that there is no S32_LE support for the codec adapter pipeline.

This is the (manual) "test case" I was asking about. It speeds up the understanding of the situation and the code review. It lets readers understand the code change even when they don't know and don't understand this codebase (and it introduces them to this codebase). It helps assess the severity of the bug fixed. Etc.

It's worth the commit message IMHO but having it in the PR is already much better than nothing.

**Review by xiulipan — APPROVED** [review]

**Comment by xiulipan** [comment]
@marc-hb @aiChaoSONG This would be a good idea to let us do some check for our lib.
I think we can try something like manually compare the result of some tplg to make sure the tplg parser work as we expected.

**Pull request merged**
