### PR TITLE
tplgtool2: style for special components in topology

### PR DESCRIPTION
**Pull request by YongAnLu00**
* dotted and blue for virtual widgets.
* dashed and orange for dynamic pipelines.

For example:
* `sof-adl-max98357a-rt5682.tplg` (virtual widgets): sof-adl-max98357a-rt5682
* `sof-tgl-nocodec.tplg` (dynamic pipelines): sof-tgl-nocodec
* `sof-hda-generic-4ch-kwd.tplg` (both dynamic pipelines and virtual widgets): sof-hda-generic-4ch-kwd

### CODE REVIEW

**Comment by aiChaoSONG** [comment]
Question: is it possible to use color? color is easier to identify than line pattern

**Comment by YongAnLu00** [comment]
@aiChaoSONG it's OK, but which color?

**Comment by aiChaoSONG** [comment]
I suggest to try several colors, and choose the ones looks best.

**Comment by marc-hb** [comment]
Use BOTH color and dot differences so it's better in color but still good in greyscale.

**Comment by marc-hb** [comment]
BTW how SOF-specific is tplgtool2? Not much is it? If not then it should submitted to ALSA. We can keep a "downstream" repo locally for faster-paced development, similar to our kernel repo. Off-topic sorry.

**Comment by YongAnLu00** [comment]
@marc-hb Only the parser `TplgBinaryFormat` _could be_ SOF-free, but most of analysis (interweaved pipelines, core id, virtual widgets, etc.) depends on SOF-specific vender tokens or naming convention.

**Comment by keyonjie** [comment]
Thanks, Looks nice improvement. @YongAnLu00 have you tried to see if it can work as expected, when the dynamic pipeline token is set different for different pipelines in the same topology?

**Comment by YongAnLu00** [comment]
@keyonjie this time I only make some of pipelines dynamic in `sof-apl-nocodec.tplg`, even this config is actually impossible, the diagram shows as expected:
sof-apl-nocodec

**Review by keyonjie — APPROVED** [review]
Thanks, nice feature, can't wait to get it.

**Review by keqiaozhang — APPROVED** [review]
Nice feature.

**Pull request merged**
