### PR TITLE
tplgtool2.py: support filesystem globbing and multiple arguments

### PR DESCRIPTION
**Pull request by marc-hb**
Warning: this is a backwards-incompatible change! The previous behavior is now available ONLY when using `--tplgroot`.

Up to now the user interface made the unusual choice to implement globbing internally instead of relying on the operating system. Maybe for compatibility with ancient .BAT scripts? So before this commit, internal globbing had to be quoted like this to escape the shell globbing, otherwise it would reject too many arguments ("unrecognized extra argument")
```
   ./tplgtool2.py 'sof-*.tplg'             # old, now INVALID usage
```
This commit adds support for multiple arguments and such quoting is not necessary anymore. HOWEVER, for backwards-compatibility the old behavior is preserved when using `--tplgroot`:
```
   ./tplgtool2.py --tplgroot . 'sof-*.tplg' # UNCHANGED behavior
```
See new --help message for more details.

Also add a number of `assert` to fix usability issue #969 and error handling when relying on the older behavior.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
I checked all the graphs in both https://sof-ci.01.org/softestpr/PR974/build64/devicetest and https://sof-ci.01.org/softestpr/PR974/build63/devicetest and they're all there.

The suspend/resume failure and the NTP failure are obviously irrelevant to this PR.

**Review by miRoox — APPROVED** [review]
LGTM,

seems related to #969.

**Review by juimonen — APPROVED** [review]
yes lgtm, fixes my issue #969 thanks!

**Comment by marc-hb** [comment]
Let's wait for the 01.org migration (and any other system-wide issue) to be resolved and then merge this.

**Review by aiChaoSONG — APPROVED** [review]

**Pull request merged**
