### PR TITLE
lib.sh: make process state check a function

### PR DESCRIPTION
**Pull request by aiChaoSONG**
Signed-off-by: Amery Song <chao.song@intel.com>

### CODE REVIEW

**Comment by xiulipan** [comment]
@aiChaoSONG Ping for update or close.

**Comment by aiChaoSONG** [comment]
@xiulipan I decide to use check_process_state function to replace sof-process-state.sh,  I think we don't need a single file for this small feature. same thing for sof-process-kill.sh.

**Comment by xiulipan** [comment]
@aiChaoSONG @marc-hb @keqiaozhang @libinyang To me the key point here is do we need standalone run for this function. Do we need this as a tool to debug with aplay/arecord process.

**Comment by aiChaoSONG** [comment]
I don't think anyone have really used this script, and for debug purpose, it is no better than the `ps`

**Comment by aiChaoSONG** [comment]
I will leave the process check as a single file, and improve the code in that file

**Pull request closed without merging**
