### PR TITLE
check-sof-logger: reload drivers first

### PR DESCRIPTION
**Pull request by marc-hb**
As we look for the FW ABI banner we must start from a clean state

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR710/build741/devicetest/ failed on
- TGLH_RVP_HDA `error: Unable to open in file /sys/kernel/debug/sof/trace: No such file or directory`
- BDW and BYT: empty DMA trace, see https://github.com/thesofproject/sof/issues/4333

**Comment by marc-hb** [comment]
> TGLH_RVP_HDA error: Unable to open in file /sys/kernel/debug/sof/trace: No such file or directory

Fixed in https://sof-ci.01.org/softestpr/PR710/build743/devicetest/ by adding a delay.

> BDW and BYT: empty DMA trace

Unchanged.

**Comment by marc-hb** [comment]
DMA trace stuck again for BDW and BYT in https://sof-ci.01.org/softestpr/PR710/build744/devicetest/, until a "nudge" gets everything out.

**Comment by marc-hb** [comment]
#711 fix should go first

**Comment by marc-hb** [comment]
In https://sof-ci.01.org/softestpr/PR710/build748/devicetest/ bug https://github.com/thesofproject/sof/issues/4333 is reproduced as usual on BDW and BYT and then worked around by this new check-sof-logger "nudge".

**Review by plbossart — APPROVED** [review]

**Comment by marc-hb** [comment]
Thanks @plbossart !

This has been in review for 7+ days and I tested this quite thoroughly. Will merge tomorrow if no objection by then.

To be clear:
- The first commit makes failure 4333 more deterministic
- The second commit "hides" it. The intention is to leave 4333 open until it is fixed (or close as wontfix)

**Review by aiChaoSONG — APPROVED** [review]

**Pull request merged**
