### PR TITLE
[CI TEST][DON'T NOT REVIEW] just for test sof-kernel-log-check: unify error filters for mei_me module 

### PR DESCRIPTION
**Pull request by keqiaozhang**

### CODE REVIEW

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Github draft?

**Comment by keqiaozhang** [comment]
PR for debugging sof-test PR test with both sof-main and stable-v2.2, almost done.

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by aiChaoSONG** [comment]
You can still test CI with a draft PR, and draft PR can not be merged

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by greg-intel** [comment]
"DON'T NOT REVIEW" is a double negative, which means it's a positive, telling us to review it...  I think you meant "DO NOT REVIEW" or "DON'T REVIEW?" 

Just in case, I reviewed it anyway.

**Comment by marc-hb** [comment]
SOFCI TEST

**Pull request closed without merging**
