### PR TITLE
Amixer setting for ipc4 platforms

### PR DESCRIPTION
**Pull request by keqiaozhang**

### CODE REVIEW

**Comment by marc-hb** [comment]
Fix for one of the shellcheck warnings suggested in https://github.com/thesofproject/sof-test/pull/1010#issuecomment-1470851805

https://github.com/thesofproject/sof-test/actions/runs/4424462565/jobs/7758320869

This other one is pretty good:

```
In case-lib/lib.sh line 811:
        APL_UP2_NOCODEC | CML_RVP_NOCODEC | JSL_RVP_NOCODEC |
TGLU_RVP_NOCODEC | ADLP_RVP_NOCODEC | TGLH_RVP_NOCODEC | MTLP_RVP_NOCODEC)



         ^--------------^ SC2221: This pattern always overrides a later one on line 819.
```

**Comment by keqiaozhang** [comment]
Passed the test on IPC3 platforms:https://sof-ci.01.org/softestpr/PR1012/build206/devicetest/index.html. No side effects.

Tested this PR on IPC4 platforms with https://github.com/intel-innersource/drivers.audio.ci.sof-framework/pull/383:

1. IPC4-CAVS2.5: https://sof-ci.ostc.intel.com/#/result/planresultdetail/22335
    Test failed on SDW platforms, it's due to known issue:https://github.com/thesofproject/sof/issues/7240

2. IPC4-ACE: https://sof-ci.ostc.intel.com/#/result/planresultdetail/22333
    All failures are identified as known issues:
    MTL-HDA: https://github.com/thesofproject/sof/issues/7298
    MTL-NOCODEC:https://github.com/thesofproject/sof/issues/6837
    MTL-SDW:https://github.com/thesofproject/sof/issues/7240

**Comment by keqiaozhang** [comment]
https://github.com/thesofproject/sof-test/pull/1010 should be merged first.

**Comment by miRoox** [comment]
Rebase?

**Comment by keqiaozhang** [comment]
> Rebase?

Done.

**Pull request merged**
