### PR TITLE
run-all-tests.sh: add $mydir to allow invoking from anywhere

### PR DESCRIPTION
**Pull request by marc-hb**
Use pwd to resolve relative paths that can be broken by symbolic links.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
>  is it better to use name like: cwd, work_dir, current_dir?

It's the location of the script so it's neither of those.

**Comment by plbossart** [comment]
see alternate solution at https://github.com/plbossart/sof-test/tree/fix/run-all-test-path

**Comment by marc-hb** [comment]
> see alternate solution at https://github.com/plbossart/sof-test/tree/fix/run-all-test-path

More specifically https://github.com/plbossart/sof-test/commit/61a50a5d73b42745b

Thanks Pierre, do you want me to resubmit with some of your code or are you going to resubmit yourself?

[ ] I can change `$0` to `BASH_SOURCE[0]`. I don't expect this script itself to be included any time soon but `BASH_SOURCE[0]` can't hurt. The `pwd` resolves relative paths, this helps when using some symbolic links. I'll keep it.
[ ] I can rename $mydir to $TEST_DIR (with quotes)

**Comment by aiChaoSONG** [comment]
@marc-hb I don't think Pierre will send his patch, could you please continue this?

**Comment by marc-hb** [comment]
> @marc-hb I don't think Pierre will send his patch, could you please continue this?

I changed `$0` to `${BASH_SOURCE[0]}`.

I didn't rename `$mydir` to `$TEST_DIR` because the name `$TEST_DIR` is better but IMHO not so much better that it's worth my time rebasing my other, local and conflicting `run-all-tests.sh` work in progress.

**Review by aiChaoSONG — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
