### PR TITLE
volume-basic-test: do not FAIL but SKIP when no PGA control

### PR DESCRIPTION
**Pull request by marc-hb**
Found and reported while testing IPC4 but probably not specific to it.

Fixes https://github.com/thesofproject/sof-test/issues/844

\+ the most obvious shellcheck fixes

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR856/build977/devicetest/?model=APL_UP2_NOCODEC_ZEPHYR&testcase=multiple-pipeline-capture and the next failures are caused by
- thesofproject/sof/issues/4414

https://sof-ci.01.org/softestpr/PR856/build977/devicetest/?model=APL_UP2_NOCODEC&testcase=check-suspend-resume-with-capture-5 is the recently resurgent
- https://github.com/thesofproject/linux/issues/3011

volume-basic-test is OK

**Review by paulstelian97 — APPROVED** [review]
Makes sense, approved.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Thanks @paulstelian97 !

@plbossart ? You asked for this in
- #844

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR856/build978/devicetest/?model=BDW_WSB_RT286&testcase=multiple-pipeline-capture looks like thesofproject/sof/issues/4859. That's a firmware bug, unrelated to this test SKIP change.

**Review by plbossart — APPROVED** [review]

**Pull request merged**
