### PR TITLE
lib.sh: add get_ldc_subdir() that follows /sys/module/snd_sof_pci/parameters/fw_path

### PR DESCRIPTION
**Pull request by marc-hb**
We need to follow the `/sys/module/snd_sof_pci/parameters/fw_path` flexibility to test the firmware as whole /lib/firmware package and to stop copying files into /etc/sof/

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR1084/build606/devicetest/index.html has 2 suspend/resume failures, https://sof-ci.01.org/softestpr/PR1084/build607/devicetest/index.html has 1.

https://sof-ci.01.org/softestpr/PR1084/build605/devicetest/index.html is amazingly all green.

**Comment by keqiaozhang** [comment]
I checked this PR with my https://github.com/thesofproject/sof-test/pull/1065 , sof-logger check passed on all CAVS platforms. But it failed on MTL platforms. please check:
https://sof-ci.ostc.intel.com/#/result/planresultdetail/29116

**Comment by marc-hb** [comment]
> But it failed on MTL platforms. please check:
https://sof-ci.ostc.intel.com/#/result/planresultdetail/29116

That's a totally different bug, unrelated to this PR. Try with this:

```diff

--- a/test-case/check-sof-logger.sh
+++ b/test-case/check-sof-logger.sh
@@ -144,7 +144,7 @@ run_loggers()
 
             loggerStatus=0; wait "$mtracetoolPID" || loggerStatus=$?
             test "$loggerStatus" -eq 124 || {
-                cat "$error_file"
+                cat "$etrace_file"
                 die "timeout $mtracetool returned unexpected: $loggerStatus"
             }
         else
```

**Comment by marc-hb** [comment]
#1086 merged, @keqiaozhang could you try again?

**Comment by keqiaozhang** [comment]
> #1086 merged, @keqiaozhang could you try again?

sof-logger check still failed on MTL and TGL-H:https://sof-ci.ostc.intel.com/#/result/planresultdetail/29206

**Comment by marc-hb** [comment]
> sof-logger check still failed on MTL and TGL-H:https://sof-ci.ostc.intel.com/#/result/planresultdetail/29206

Yes but now it's showing the real mtrace problem which means we should merge this test PR :-)

```
Traceback (most recent call last):
  File "/usr/local/bin/mtrace-reader.py", line 20, in 
    fd = os.open(MTRACE_FILE, os.O_RDONLY)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/sof/mtrace/core0'
```

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Just one unrelated pause/resume failure in https://sof-ci.01.org/softestpr/PR1084/build645/devicetest/index.html

Just one well known and unrelated UP2 topology issue in https://sof-ci.01.org/softestpr/PR1084/build644/devicetest/index.html?model=APL_UP2_NOCODEC&testcase=verify-tplg-binary

Everything else green.

**Review by keqiaozhang — APPROVED** [review]
Tested.

**Comment by marc-hb** [comment]
Thanks @keqiaozhang !

**Pull request merged**
