### PR TITLE
Small log collection refactor to prepare catching fw errors

### PR DESCRIPTION
**Pull request by marc-hb**
3 commits

Preparation for #1075, only one small functional change: counting the number of lines in mtrace.txt

### CODE REVIEW

**Comment by marc-hb** [comment]
Only suspend/resume failures in 
https://sof-ci.01.org/softestpr/PR1076/build541/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1076/build540/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1076/build539/devicetest/index.html

**Review by fredoh9 — APPROVED** [review]
Looks good. Approved.

One curious thing, I checked the results, one of failure in MTL test. mtrace lines is 178 but nlines=176. Not a big deal but looks first and last lines are new lines?

reference link: planresultdetail/28427?model=MTLP_RVP_NOCODEC&testcase=check-suspend-resume-with-capture-5

**Review by keqiaozhang — APPROVED** [review]
LGTM

**Review by greg-intel — APPROVED** [review]

**Comment by marc-hb** [comment]
thanks for the very prompt reviews!

> mtrace lines is 178 but nlines=176. 

There is probably something funny the web interface does. The number comes from a bare `wc -l` so that bit is to simple to be buggy.

**Pull request merged**
