### PR TITLE
verify-kernel-boot-log.sh: re-enable on ADL

### PR DESCRIPTION
**Pull request by marc-hb**
Logical revert of 2021 commit e1b364a57388d

### CODE REVIEW

**Comment by marc-hb** [comment]
Unrelated `e1000e` error in https://sof-ci.01.org/softestpr/PR1116/build827/devicetest/index.html

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by fredoh9 — APPROVED** [review]
Looks good

**Comment by marc-hb** [comment]
Thanks @fredoh9 . Very small and super low risk change in review for 2 days, merging

**Pull request merged**
