### PR TITLE
Add support for topologies and .ldc files in /lib/firmware/updates …

### PR DESCRIPTION
**Pull request by marc-hb**
2 commits. 1 bug fix, 1 main feature

Required by SOF install commit 65ade5a4f973 ("installer: change default
destination to /lib/firmware/updates"), see
thesofproject/sof#4020

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR645/build642/devicetest/?model=CML_HEL_RT5682&testcase=verify-pcm-list failed because the command `sof-test/tools/sof-tplgreader.py /lib/firmware/intel/sof-tplg/sof-cml-rt1011-rt5682.tplg  -d id pcm type -o` printed:
```
id=8;pcm=DMIC16k;type=capture;
```
instead of:
```
id=8;pcm=DMIC16kHz;type=capture;
```
In case anyone wonders, I checked and found no `/lib/firmware/updates/` directory on `jf-cml-hel-rt5682-03` (I don't expect any such directory anywhere)

@ranj063  any clue?

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR645/build643/devicetest/?model=TGLH_RVP_HDA&testcase=check-suspend-resume-5 is unrelated `e1000e 0000:00:1f.6 enp0s31f6: Hardware Error`. @XiaoyunWu6666  could you or someone in SH disable this interface in the BIOS of `sh-tglh-rvp-hda-05`?

The previous `id=8;pcm=DMIC16k;type=capture;` did not happen on this different system: `sh-cml-hel-rt5682-05`

> In case anyone wonders, I checked and found no /lib/firmware/updates/ directory on jf-cml-hel-rt5682-03 (I don't expect any such directory anywhere)

Unless... someone borrowed a system and left some `/lib/firmware/updates/intel/sof*` directories there. Then we would be in big trouble after this PR gets merged, so reverting to a draft. @aiChaoSONG , @fredoh9 where in the deployment scripts can we make sure ``/lib/firmware/updates/intel/sof*` are cleared?

**Comment by keqiaozhang** [comment]
> https://sof-ci.01.org/softestpr/PR645/build643/devicetest/?model=TGLH_RVP_HDA&testcase=check-suspend-resume-5 is unrelated `e1000e 0000:00:1f.6 enp0s31f6: Hardware Error`. @XiaoyunWu6666 could you or someone in SH disable this interface in the BIOS of `sh-tglh-rvp-hda-05`?

I will handle this, looks like I forgot to disable the onboard network port for this device.

**Review by aiChaoSONG — APPROVED** [review]
After this change, we also need to let CI to deploy binaries to the corresponding folder(s)

**Comment by marc-hb** [comment]
Another problem noticed: logs often don't show the full path "firmware" files are loaded from. This needs to be addressed first.

**Comment by marc-hb** [comment]
discussion on alsa-devel https://mailman.alsa-project.org/pipermail/alsa-devel/2021-April/183327.html

**Comment by marc-hb** [comment]
No time for this right now, will re-open if priorities change.

**Pull request closed without merging**
