### PR TITLE
check-kmod-load-unload: use TOPDIR, don't rely on PATH 

### PR DESCRIPTION
**Pull request by marc-hb**
This was apparently the only test in run-all-tests.sh that required a PATH change.

### CODE REVIEW

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR808/build924/devicetest/?model=APL_UP2_NOCODEC&testcase=check-suspend-resume-with-capture-5 is 5.6-rc1 regression https://github.com/thesofproject/linux/issues/3283

The alsabat failure is also unrelated, this PR changes only one, different test.

**Comment by marc-hb** [comment]
Big regressions in https://sof-ci.01.org/softestpr/PR808/build927/devicetest/ unrelated to this, see thesofproject/linux#3292 for more details.

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by greg-intel** [comment]
I'm not sure of the specific intent, but all the changes more or less make sense to me.  I don't see any obvious issues, assuming the following isn't related:
`2021-11-24 04:16:00 UTC Sub-Test: [REMOTE_ERROR] Caught error in kernel log
2021-11-24 04:16:00 UTC Sub-Test: [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2021-11-24 04:16:00 UTC Sub-Test: [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2021-11-24 04:16:00 UTC Sub-Test: [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume.sh:91
2021-11-24 04:16:00 UTC Sub-Test: [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume.sh:91
2021-11-24 04:16:00 UTC Sub-Test: [REMOTE_INFO] Test Result: FAIL!`

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR808/build929/devicetest/?model=CML_RVP_SDW&testcase=check-suspend-resume-with-playback-5 is "preemptible" BUG https://github.com/thesofproject/linux/issues/3283

`sh-cml-sku0955-hda-02` crashed in the middle of the test run _before_ running this test, so unrelated.

Everything else is green.

**Comment by greg-intel** [comment]
Last question, @marc-hb, Did the GitHub actions test these script changes?

**Review by greg-intel — APPROVED** [review]
Changes look fairly straightforward.

**Comment by marc-hb** [comment]
Minor, zero functional change up for 10 days in review : merging.

**Pull request merged**
