### PR TITLE
[SKIP CI] lib.sh: replace with axfer for playback and capture

### PR DESCRIPTION
**Pull request by fredoh9**
WIP: Initial attempt. Need to check how much change is required and
axfer is better in terms of SOF CI automation.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

### CODE REVIEW

**Comment by fredoh9** [comment]
There are some more places to replace aplay/arecord command.

**Comment by marc-hb** [comment]
https://sof-ci.01.org/softestpr/PR938/build88/devicetest/ shows compatibility issues.

If we ever switch I think we should switch more gradually, on a test by test basis.

Also, can `axfer` reproduce thesofproject/linux/issues/3766 like `arecord` does?

**Comment by fredoh9** [comment]
> If we ever switch I think we should switch more gradually, on a test by test basis.

I agree

**Comment by fredoh9** [comment]
put [SKIP CI] because check-signal-stop-start is not being used by PR testing.

Piggyback on check-signal-stop-start.sh to test signal pause/resume with Axfer.
The test results are PASS but there are some
`Fail to process frames: Interrupted system call`

Will look at that later.

https://github.com/thesofproject/alsa-utils/blob/a566f8a0ed6d7ca5fd6ae2d224f3f28654a2f3be/axfer/xfer-libasound.c#L784

[check-signal-pause-resume-test-axfer.txt](https://github.com/thesofproject/sof-test/files/9136152/check-signal-pause-resume-test-axfer.txt)
.

**Comment by fredoh9** [comment]
will close for now, will re-visit later when available.

**Pull request closed without merging**
