### PR TITLE
verify-ucm-config :remove limitation of ucm2

### PR DESCRIPTION
**Pull request by libinyang**
Remove the limitation of ucm2 to support ucm2 configurations.

### CODE REVIEW

**Comment by libinyang** [comment]
Now as ucm2 is supported by alsa-lib and pulseaudio, we can remove the ucm2 support limitation in our sof-test.

**Comment by libinyang** [comment]
@Bin-QA @keqiaozhang @aiChaoSONG Please help review

**Comment by xiulipan** [comment]
@libinyang do we have UCMs for some test now?

**Comment by libinyang** [comment]
@xiulipan Yes. The upstream alsa-ucm-conf has a default ucm2. I tested upstreamed ucm2 config with verify-ucm-config.sh on cml-rvp-hda platforms, and it works. I'm still developing the ucm configs on APL UP2 NOCODEC, BYT MB NOCODEC, BYT MB RT5682, APL UP2 PCM512X, GLK BOB DA7219
 
> @libinyang do we have UCMs for some test now?

**Pull request merged**
