### PR TITLE
kmod: add more SoundWire codecs

### PR DESCRIPTION
**Pull request by plbossart**
rt722-sdca, rt1017-sdca and CirrusLogic missing

Note for for CirrusLogic we may have additional dependencies on MFD stuff.

### CODE REVIEW

**Comment by marc-hb** [comment]
Warning: "all checks have passed" is misleading: sof-test has NOT run yet. Internal throttling issue 480

**Review by marc-hb — DISMISSED** [review]

**Comment by marc-hb** [comment]
check-kmod-load-unload.sh failures across the boards in both stable-v2.2 and cavs25

https://sof-ci.01.org/softestpr/PR1110/build777/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1110/build778/devicetest/index.html

Most or maybe all of them are:
```
rmmod: ERROR: Module snd_soc_cs42l43_sdw is in use by: snd_soc_cs42l43
```

**Comment by plbossart** [comment]
@charleskeepax @rfvirgil any idea why the dependencies are different between CS42l43 and other codecs?

**Comment by charleskeepax** [comment]
The error message you state seems expected to me:

snd_soc_cs42l43 - this is the core modules holds the control bus independent code.
snd_soc_cs42l43_sdw - this is the soundwire modules holds stuff specific to soundwire.

I would expect you would need to remove the core module before you remove the soundwire one as the core calls into the soundwire code for things like dai ops. One could theoretically arrange the code the other way around but it gets really messy with having to have duplicate dai_driver struct etc.

**Comment by charleskeepax** [comment]
I guess the difference here is the actual bus level code would be the other way around (soundwire code calls the core), but since cs42l43 is an MFD the bus level code lives in MFD.

**Comment by plbossart** [comment]
Thans @charleskeepax I inverted the order, let's see how things go.

**Comment by marc-hb** [comment]
Now fails most cavs2.5 and stable-v2.2 like this:
https://sof-ci.01.org/softestpr/PR1110/build782/devicetest/index.html
```
rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_wm_adsp
```

Just realized this test hasn't been re-added to ACE yet:
- https://github.com/thesofproject/sof-test/issues/1037#issuecomment-1753586703

**Review by bardliao — APPROVED** [review]

**Comment by marc-hb** [comment]
SOFCI TEST

**Review by marc-hb — CHANGES_REQUESTED** [review]
Now MTL/ACE is failing like the others:
https://sof-ci.01.org/softestpr/PR1110/build791/devicetest/index.html?model=MTLP_RVP_SDW&testcase=check-kmod-load-unload

```
RMMOD	snd_soc_core
rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_wm_adsp
```

**Comment by fredoh9** [comment]
SOFCI TEST
new daily kernel build is available.

**Comment by fredoh9** [comment]
new daily kernel build is available. Triggered new test again

**Comment by fredoh9** [comment]
the device test is going on, no MTLP_RVP_NOCODEC. jf-mtlp-rvp-nocodec-2 had apt package tangled problem. fixed on the device

**Comment by marc-hb** [comment]
Thanks @fredoh9 .

Still failing in https://sof-ci.01.org/softestpr/PR1110/build796/devicetest/index.html , https://sof-ci.01.org/softestpr/PR1110/build794/devicetest/index.html and https://sof-ci.01.org/softestpr/PR1110/build795/devicetest/index.html of course, no change
```
RMMOD	snd_soc_core
rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_wm_adsp
```

**Comment by marc-hb** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
Still failing with `rmmod: ERROR: Module snd_soc_core is in use by: snd_soc_wm_adsp` across https://sof-ci.01.org/softestpr/PR1110/build411/devicetest/index.html
and in https://sof-ci.01.org/softestpr/PR1110/build410/devicetest/index.html and inhttps://sof-ci.01.org/softestpr/PR1110/build794/devicetest/index.html,...

**Comment by marc-hb** [comment]
There is a git conflict now.

**Comment by marc-hb** [comment]
@bardliao could you rebase and resubmit this?

**Comment by bardliao** [comment]
> @bardliao could you rebase and resubmit this?

sure

**Comment by bardliao** [comment]
https://github.com/thesofproject/sof-test/pull/1235

**Pull request closed without merging**
