### PR TITLE
tplgtool: implement enum kcontrol parsing function

### PR DESCRIPTION
**Pull request by aiChaoSONG**
Previously, the _enum_ctrl_parse() is left unimplemented
because we don't have enum kcontrol in existing topologies.

The new component TDFB is introduced recently, and requires
enum kcontrol to be parsed.

This patch implements the _enum_ctrl_parse function to
support enum kcontrol parsing.

Signed-off-by: Chao Song <chao.song@linux.intel.com>

### CODE REVIEW

**Comment by aiChaoSONG** [comment]
@singalsu The previously version of this tool doesn't implement the enum kcontrol parsing feature, and caused the issue you raised up. This patch add the implementation, and align with the existing coding style.

@thesofproject/test-maintainers This tool can date back to the early days after I join Intel several months, this tool is my starter project to SOF and ALSA. the code may looks ugly because I am not very familiar with ASoC structures.  I have plan to optimize or rewrite this tool, don't review so much.

**Review by xiulipan — APPROVED** [review]
For byte reader, I will suggest you to take a look at https://github.com/thesofproject/sof/blob/master/tools/sof_ri_info/sof_ri_info.py

That would avoid to use hard code offset by read the binary as a stream.

**Comment by marc-hb** [comment]
> The new component TDFB is introduced recently, and requires enum kcontrol to be parsed.

@aiChaoSONG  does this mean there will be some CI coverage for this new code? If not it will "bitrot".

> https://github.com/thesofproject/sof/blob/master/tools/sof_ri_info/sof_ri_info.py
> That would avoid to use hard code offset by read the binary as a stream.

@xiulipan do you mean relative offsets as opposed to absolute offsets in `bytes_data[]`?

 `sof_ri_info.py` would be much shorter and easier to read if it were using the reader concept for relative offsets _and_`struct` too inside its functions. For instance `parse_css_manifest_4()` could half the size if it were using `read_bytes()` at the start and then a few `struct` internally.

Afraid another problem with  `sof_ri_info.py` is the lack of test coverage, is there any?

**Comment by aiChaoSONG** [comment]
> does this mean there will be some CI coverage for this new code? If not it will "bitrot"

@marc-hb Currently, no. All of our existing typologies don't contains any component that requires enum kcontrol, so this function is left unimplemented before, because it will never be called. But recently, @singalsu is working on TDFB component and finds the tool cannot work, so I add implementation in this PR, and test it with his topology. As stated, it is will not be called before any topology with enum kcontrol is used.
sof-cml-rt1011-rt5682-tdfb_68mm-2ch

**Comment by marc-hb** [comment]
Thanks, so rephrasing my question: no automated TDFB test that will regularly run this PR in the (distant?) future? Just wondering.

**Comment by aiChaoSONG** [comment]
> Thanks, so rephrasing my question: no automated TDFB test that will regularly run this PR in the (distant?) future? Just wondering.

It depends on when will Seppo's TDFB component get merged to SOF. once merged, we will have topology with TDFB which have enum kcontrol inside, so the code in this PR will tested daily.

**Review by singalsu — APPROVED** [review]
Thanks! The decoded graphical topology view is correct.

**Pull request merged**
