### PR TITLE
check-sof-logger: partially re-enable for Zephyr 

### PR DESCRIPTION
**Pull request by marc-hb**
Re-enable only for the DMA trace.

\+ fix error handling in run_loggers function

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]
Looks good!

**Comment by marc-hb** [comment]
Thanks @kv2019i ! 5 days in review; merging

**Comment by YongAnLu00** [comment]
check-sof-logger failed on all the Zephyr devices in today's daily test, maybe sof-logger is still not ready for Zephyr?

**Comment by marc-hb** [comment]
sof-logger has been used with Zephyr by @kv2019i , @lyakh, myself and many others for a few months. Also, I know it may sound unusual but I tested this PR fairly thoroughly before submitting it.
```
2021-11-10 21:26:12 UTC [REMOTE_INFO] Looking for ldc File ...
2021-11-10 21:26:12 UTC [REMOTE_INFO] Found file: /etc/sof/sof-tgl-h.ldc d41d8cd98f00b204e9800998ecf8427e
...
...
error: Error while reading /etc/sof/sof-tgl-h.ldc.
```
I don't have any proof yet but suspect a deployment mixup between the XTOS .ldc file and Zephyr .ldc file. Our deployment scripts are internal and overly complicated. They should be neither and they should not deploy the .ldc file to `/etc`, see internal issue 151

**Comment by keqiaozhang** [comment]
@marc-hb, I did a quick check, zephyr platforms can pass the sof-logger test, so looks like we use the wrong .ldc file in our deployment. I will debug it.

**Comment by marc-hb** [comment]
> I don't have any proof yet but suspect a deployment mixup between the XTOS .ldc file and Zephyr .ldc file. 

Even more suspicion after this:

```shell
$ ls -lt /lib/firmware/intel/sof/*tgl-h* /lib/firmware/intel/sof/*/*tgl-h* /etc/sof/*tgl-h*

-rw-r--r-- 1 root root 5947449 Nov 11 21:29 /etc/sof/sof-tgl-h.lst
lrwxrwxrwx 1 root root      36 Nov 11 21:28 /lib/firmware/intel/sof/community/sof-tgl-h.ri -> /lib/firmware/intel/sof/sof-tgl-h.ri
-rw-r--r-- 1 root root  418528 Nov 11 21:28 /lib/firmware/intel/sof/sof-tgl-h.ri
-rw-r--r-- 1 root root   98568 Nov 11 21:18 /etc/sof/sof-tgl-h.ldc
```

Above you can see the .ldc file is 10 minutes older than the other files. Now let's do some grepping:

```shell
$ grep -c  zephyr /lib/firmware/intel/sof/*tgl-h* /lib/firmware/intel/sof/*/*tgl-h* /etc/sof/*tgl-h*

/etc/sof/sof-tgl-h.lst:546
/lib/firmware/intel/sof/sof-tgl-h.ri:15
/etc/sof/sof-tgl-h.ldc:0
```

Just to be on the safe side:
```shell
strings /etc/sof/sof-tgl-h.ldc | grep -c zephyr
0
```

**Comment by keqiaozhang** [comment]
I have submitted the patches to fix this issue:
https://github.com/intel-innersource/drivers.audio.ci.sof-jenkins/pull/65
https://github.com/intel-innersource/drivers.audio.ci.sof-sh/pull/39
Test report can be found here:https://sof-ci.sh.intel.com/#/result/planresultdetail/8136

**Pull request merged**
