### PR TITLE
kmod: remove snd_soc_sof_sdw before removing snd_soc_hdac_hdmi

### LINKED ISSUE #142: BUG][CML-SDW]kmod load/unload script need to change
on  CML RVP SDW
the daily base test  case "Check kmod load/unload" failed,because Module snd_soc_hdac_hdmi is in use by: snd_soc_sof_sdw when remove
http://sof-tcr.sh.intel.com/#/tests/4579f985-3d33-4db0-856a-c250a9c7fefe/detail

Capture
need to change the script to remove snd_soc_sof_sdw before remove snd_soc_hdac_hdmi

### PR DESCRIPTION
**Pull request by aiChaoSONG**
This patch fixes "Module snd_soc_hdac_hdmi is in use
by: snd_soc_sof_sdw" when removing snd_soc_hdac_hdmi.

fixes #142 and #146

Signed-off-by: Amery Song <chao.song@intel.com>

### CODE REVIEW

**Comment by aiChaoSONG** [comment]
DO NOT MERGE before Pierre's Review

**Comment by aiChaoSONG** [comment]
@plbossart is snd_soc_rt1308_sdw renamed to snd_soc_rt1308? we got #146. And I am not sure if I place snd_soc_sof_sdw into the correct place, please review.

**Comment by RanderWang** [comment]
> @plbossart is snd_soc_rt1308_sdw renamed to snd_soc_rt1308? we got #146. And I am not sure if I place snd_soc_sof_sdw into the correct place, please review.

No.  snd_soc_rt1308 is for I2S mode.

**Comment by aiChaoSONG** [comment]
fixed by pierre in another commit, close

**Pull request closed without merging**
